language: node_js
node_js:
- node
services:
- mongodb
before_script:
- npm start&
deploy:
  api_key:
    secure: Lcclnz8cuv9JW5zBE2YNnIgkOE5JOcn5WX3xtoYMtxnLScM0HfJRsxipo16ipZsSo4KuAv2So2WmDcfSEcLoQZGSdv4XkN0gDAQNlo4XVyeI4bp9PuyTGR4UpjIUUtYa43ZbQI5T9s02RWb9FcKXFWKRWN5/KZPW6P8wTyNn4xIHD4l6wTfVlHG8Bi2/zgIp7EzH58gus5yNCt96O/F4XqpbMF4sGiFcctkHcNk/DXSDIJ/E06SfShfMSdN89vIMo6UdLfZQk52iGcAELqT9TCV1VlgBgr/7ta7yZYsAq1pTm/gpT4/OGt5RdJ6gQ2QcaVj+KhZh1Dz4tinbO0JM8JNz2IG/9esaOvwJcslKIx8rWeDqNBxQEfczVYCb5v07cEFyfBYd+UYLcgG7xmnSxcu1QLNjOmkIm8yxF2RxmRsL1f/94G+VGhok7LeUSbc5wsPnZtS21cBTLYEZGrBLMHynSoeuSo7J/S0ePmhJkEZAliS/Ixo4NITVf4fdUYuy1qhjTecRj4wJfRKDnr0BwjKDnS2wWeI5uaFFAtgDxwmZTiCZIK3RnaQv3po8swEE8ruIH5jbOj6vxi85WF1q9xpI8qh8+ne7lrWNEp9PO843A3O8IIiOwBgxrASbiypo4KUGUkNeLPAaYeS0xYhgybTbxsim/CRgjqsYg6iiXfI=
